apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: product-service
build:
  artifacts:
    - image: pcpartsshop/product-service
      docker:
        dockerfile: Dockerfile
  local: {}
manifests:
  rawYaml:
    - k8s/app*
    - k8s/psql*
    - k8s/rabbit*
    - k8s/redis*
